epochs: 100
units: [128, 128]
metrics: ['mse', 'mape', 'mae']
loss: 'mse'
optimizer: adam
roll_period: 30
normalizer: 1
classification: False
batch_size: 32
skip: 1
n: 10
m: 5
shift: 5
hop: 0.25
patience: 5

